apiVersion: v1
kind: Pod
metadata:
  name: copier
  labels:
    tier: node
    app: cni-copier
    name: cni-copier
spec:
  restartPolicy: OnFailure
  nodeName: qvm-wz-dora1
  tolerations:
    - operator: Exists
      effect: NoSchedule
    - operator: Exists
      effect: NoExecute
  containers:
    - name: copier
      image: zengxu/cni-copier:7e9ada5
      imagePullPolicy: Always
      env:
        - name: CNI_BIN_SRC
          value: /opt/cni/bin
        - name: CNI_BIN_DST
          value: /host/opt/cni/bin
        - name: OVERRIDE
          value: "true"
      resources:
        requests:
          cpu: "10m"
          memory: "15Mi"
      securityContext:
        privileged: true
      volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
  terminationGracePeriodSeconds: 10
  volumes:
    - name: cnibin
      hostPath:
        path: /opt/cni/bin
